# Generated by Django 5.0.1 on 2024-05-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0003_hourssettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="discord",
            field=models.URLField(
                blank=True, help_text="Enter general discord or a invite link"
            ),
        ),
    ]
