# Generated by Django 5.0.1 on 2024-05-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0004_socialmediasettings_discord"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterCTASettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=250)),
                ("button_text", models.CharField(default="Contact Us", max_length=25)),
                (
                    "button_external_page",
                    models.URLField(
                        blank=True,
                        help_text="If an internal page is selected, it will be used before the external page.",
                    ),
                ),
                (
                    "button_internal_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="If an internal page is selected, it will be used before the external page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
