# Generated by Django 5.0.1 on 2024-01-22 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image",
            field=models.ForeignKey(
                help_text="The banner background image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an optional page to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Button text", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lead_text",
            field=models.CharField(
                blank=True,
                help_text="Subheading text under the banner title",
                max_length=140,
            ),
        ),
    ]
